x = input('Digite algo: ')
print('contem somente números ?', x.isnumeric())
print('contem somente letras ?', x.isalpha())
print('contem somente letras em maiusculo ?', x.isupper())
print('contem somente letras em minusculo ?', x.islower())
print('contem letras e/ou numeros ?', x.isalnum())
print('contem um número decimal ?', x.isdecimal())
print('é algaritmo da tabela ascii ?', x.isascii())
print('', x.isidentifier())